spring:
  #  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/flower?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
mybatis:
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8080
  servlet:
    context-path: /api/demo


