spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.92.100:1521:orcl
    driver-class-name: oracle.jdbc.OracleDriver
    username: web
    password: 123456
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:config/mybatis/mybatis-config.xml
  #检查配置文件是否存在
  check-config-location: true

server:
  port: 8080
  servlet:
    context-path: /api/demo


